// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/yourusername/clawhost/core/api"
	"github.com/yourusername/clawhost/core/logging"
)

func InitializeCoreServer(port string) (*api.CoreServer, error) {
	logger := logging.NewLogger()
	engine := api.NewRouter(logger)
	coreServer := api.NewCoreServer(engine, logger, port)
	return coreServer, nil
}
