package examples
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"time"

	mcp "clawhost/mcp-bridge"
)

func main() {
	// Initialize logger
	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: slog.LevelDebug,
	}))
	slog.SetDefault(logger)














































































































































































































}	_ = slackServer	// but they remain hidden from the parent process's logs and the LLM's view	// Once injected into the subprocess, the server can use these environment variables	)		nil,		},			// These NEVER appear in logs or responses			"SLACK_APP_TOKEN": os.Getenv("SLACK_APP_TOKEN"),			"SLACK_BOT_TOKEN": os.Getenv("SLACK_BOT_TOKEN"),		map[string]string{		[]string{"slack-mcp-server.js"},		"node",		"slack",	slackServer := mcp.NewMCPServer(	// - .env file (development only)	// - Kubernetes Secrets	// - HashiCorp Vault	// - AWS Secrets Manager	// These would typically come from:func ExampleSecureEnvironment() {// ExampleSecureEnvironment demonstrates environment variable injection safety.}	// result, err := registry.ExecuteTool(ctx, toolID, userParams)	// toolID := "slack_send_message"	// When the LLM requests to use a tool, you'd look it up like:	fmt.Printf("LLM Tool Manifest:\n%s\n", string(toolsJSON))	toolsJSON, _ := json.MarshalIndent(tools, "", "  ")	// This would be sent to the LLM as part of the system prompt	tools := registry.GetAllToolsForLLM()	// Get all tools formatted for OpenAI/Claude APIfunc ExampleToolRegistry(registry *mcp.ToolRegistry) {// ExampleToolRegistry demonstrates building an LLM-compatible tool manifest.}	}		}			fmt.Println("  Request timeout!")		case <-time.After(6 * time.Second):			fmt.Printf("  %s\n", result)		case result := <-resultChan:		select {	for i := 0; i < numRequests; i++ {	// Collect results	}		}(i)			resultChan <- fmt.Sprintf("Request %d (server: %s): SUCCESS", requestNum, serverName)			}				return				resultChan <- fmt.Sprintf("Request %d (server: %s): RPC Error - %s", requestNum, serverName, resp.Error.Message)			if resp.Error != nil {			}				return				resultChan <- fmt.Sprintf("Request %d (server: %s): ERROR - %v", requestNum, serverName, err)			if err != nil {			resp, err := bridge.RouteRequest(ctx, serverName, req)			}				Params:  json.RawMessage(`{}`),				Method:  "tools/list",				ID:      int64(requestNum),				JSONRPC: "2.0",			req := &mcp.JSONRPCRequest{			// Create a sample tools/list request			}				serverName = "postgres"			if requestNum%2 == 0 {			serverName := "slack"			// Alternate between servers to show routing			defer cancel()			ctx, cancel := context.WithTimeout(baseCtx, 5*time.Second)		go func(requestNum int) {	for i := 1; i <= numRequests; i++ {	// Issue multiple concurrent requests	resultChan := make(chan string, numRequests)	// Create a channel for results	const numRequests = 5func demonstrateConcurrency(baseCtx context.Context, bridge *mcp.Bridge, registry *mcp.ToolRegistry, logger *slog.Logger) {// demonstrateConcurrency shows how the bridge handles concurrent requests.}	demonstrateConcurrency(context.Background(), bridge, registry, logger)	fmt.Println("\n=== Concurrent Requests Demo ===")	// Demonstrate concurrent requests	}		fmt.Printf("%s: %s\n", server, statusStr)		}			statusStr = "unhealthy"		if !status {		statusStr := "healthy"	for server, status := range health {	health := bridge.HealthCheck()	fmt.Println("\n=== Server Health ===")	// Display health status	}		}			fmt.Printf("Tool result: %v\n", result)		} else {			logger.Error("tool_execution_failed", slog.String("tool", toolID), slog.Any("error", err))		if err != nil {		cancel()		result, err := registry.ExecuteTool(ctx, toolID, params)		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)		params := json.RawMessage(`{"channel":"#general","text":"Hello from MCP Bridge!"}`)		// Sample params (these would come from the LLM in real usage)		toolID := fmt.Sprintf("slack_%s", slackTools[0].OriginalName)	if len(slackTools) > 0 {	fmt.Println("\n=== Executing Sample Tool Call ===")	// Example: Execute a tool (e.g., Slack message)	}		fmt.Printf("- %s: %s\n", tool.OriginalName, tool.Description)	for _, tool := range postgresTools {	postgresTools := registry.GetToolsByServer("postgres")	fmt.Println("\n=== Postgres Tools ===")	// Example: Get all Postgres tools	}		fmt.Printf("- %s: %s\n", tool.OriginalName, tool.Description)	for _, tool := range slackTools {	slackTools := registry.GetToolsByServer("slack")	fmt.Println("\n=== Slack Tools ===")	// Example: Get all Slack tools	}		fmt.Printf("[%d] %v\n", i+1, tool)	for i, tool := range tools {	tools := registry.GetAllToolsForLLM()	fmt.Println("\n=== Available Tools for LLM ===")	// Print all available tools in LLM format	logger.Info("registry_refreshed", slog.Any("stats", registry.GetStats()))	cancel()	}		os.Exit(1)		cancel()		logger.Error("failed to refresh registry", slog.Any("error", err))	if err := registry.Refresh(ctx); err != nil {	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)	// Fetch available tools	registry := mcp.NewToolRegistry(bridge, logger)	// Initialize tool registry	logger.Info("postgres_server_registered")	}		os.Exit(1)		logger.Error("failed to register postgres server", slog.Any("error", err))	if err := bridge.RegisterServer(postgresServer); err != nil {	)		logger,		},			"DATABASE_URL": os.Getenv("DATABASE_URL"),		map[string]string{		[]string{"@postgres/mcp-server"},		"npx",		"postgres",	postgresServer := mcp.NewMCPServer(	// Example 2: Register Postgres MCP Server	logger.Info("slack_server_registered")	}		os.Exit(1)		logger.Error("failed to register slack server", slog.Any("error", err))	if err := bridge.RegisterServer(slackServer); err != nil {	)		logger,		},			"SLACK_APP_TOKEN": os.Getenv("SLACK_APP_TOKEN"),			"SLACK_BOT_TOKEN": os.Getenv("SLACK_BOT_TOKEN"),		map[string]string{		[]string{"@slack/mcp-server-slack"},		"npx",		"slack",	slackServer := mcp.NewMCPServer(	// Example 1: Register Slack MCP Server	}()		}			logger.Error("bridge_close_failed", slog.Any("error", err))		if err := bridge.Close(ctx); err != nil {		defer cancel()		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)	defer func() {	bridge := mcp.NewBridge(logger)	// Create bridge instance